name: CI
on:
  push:
    branches: [ "cicd_207315" ]

  workflow_dispatch:

jobs:
  tests_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6

      - name: Run tests
        run: python -m unittest circle_tests.py rectangle_tests.py square_tests.py triangle_tests.py
  tests_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11.6
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6

      - name: Run tests
        run: python -m unittest circle_tests.py rectangle_tests.py square_tests.py triangle_tests.py
